branches:
  - main
  - master
preset: "angular"
debug: true
ci: true
dryRun: false
extends: "semantic-release-npm-github-publish"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - "@semantic-release/github"
analyzeCommits:
    - path: "@semantic-release/commit-analyzer"
      releaseRules:
        - type: "*"
          release: "patch"
        - message: "*"
          release: patch
        - subject: "*"
          release: patch
        - type: "feat"
          release: minor
      presetConfig: true
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "feat"
        - "perf"
        - "fix"
      commitsSort: "header"
    types:
      - type: "feat"
      - section: "Features"
      - type: "*"
      - section: "Bug Fixes"
    presetConfig: true
