branches:
  - main
  - master
preset: "angular"
debug: true
ci: true
dryRun: false
extends: "semantic-release-npm-github-publish"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - "@semantic-release/github"
analyzeCommits:
    - path: "@semantic-release/commit-analyzer"
      preset: angular
      releaseRules:
        - type: "*"
          release: "patch"
