name: npm-build-publish
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
#  release:
#    name: Release
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Set up git
#        run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: "lts/*"
#      - name: Install dependencies
#        run: npm ci
#      - name: Release
#        run: |
#          npm run release
#          rm -rf CHANGELOG.md
#          git push --force-with-lease
#      - name: Push
#        run: git push --force-with-lease
