name: npm-build-publish
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm install
      - run: npx semantic-release
      - run: cat package.json
      - run: git status
#  release:
#    name: Release
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Set up git
#        run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: "lts/*"
#      - name: Install dependencies
#        run: npm ci
#      - name: Release
#        run: |
#          npm run release
#          rm -rf CHANGELOG.md
#          git push --force-with-lease
#      - name: Push
#        run: git push --force-with-lease
