name: npm-build-publish
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm i --lockfile-version 1
      - run: npx semantic-release
